### ISSUE TITLE
Reasons for nested svg

### ISSUE THREAD

**Issue by busti** [depuits/ned#1]
Hello,  

is there a reason for the nodes being separate svgs? I could not find any other web node editor library that was purely svg based and am really curious.  
I am working on a similar project, but, unfortunately I cannot use your library as my architecture is way different.

Thanks in advance.

**Comment by depuits** [comment]
Because the nested [`<svg>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg) elements create their own coordinate system which the [`<g>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/g) doesn't do. This allows me to use local coordinates the determine the placement of elements inside a node. 

The same could probable be achieved if you use transforms for the placement of the nodes instead of the x and y attributes ([which might actually be preferred](https://stackoverflow.com/q/15989854/1018842)).

I haven't used this library myself in another project yet, so it could be that the architecture of the library isn't a great fit for the real world. Suggestions are always welcome.

**Comment by busti** [comment]
Thank you very much. This helps a lot.
I am not actually in a js environment, so I am unable to use the library.

Thanks again for your answer, you may close this issue.
